language: php

php:
  - 5.6

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

sudo: false

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction

script:
  - vendor/bin/phpunit